### ISSUE TITLE
jetpack 4.5 support

### ISSUE THREAD

**Issue by vincentkieboom** [otamajakusi/dockerfile-yolov5-jetson#1]
Hey thanks for publishing this, awesome work! Because jetpack 4.5 is now I got an issue with the current dockerfile, but changing the first line to nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.6-py3 fixed this.

**Comment by otamajakusi** [comment]
Ok, I'd like to confirm it!

**Comment by otamajakusi** [comment]
52b0f2d3edcf1bcbaa950c9e77db3c98a5489fe0 fixes this issue. Thanks!
