### ISSUE TITLE
Purpose of the Dockerfile Base Image if we are installing torch and torchvision?

### ISSUE THREAD

**Issue by joneswilliam1** [otamajakusi/dockerfile-yolov5-jetson#11]
Hi @otamajakusi, sorry if this question is rather unintellectual but may I know what is the purpose of having this base image:
 ```FROM nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.6-py3``` instead of SCRATCH since it only comes with torch and torchvision packages and we are already installing those in the Dockerfile? Would love some clarification from you. Thanks again!

**Comment by otamajakusi** [comment]
@joneswilliam1 Oh, I think you're correct. `nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.6-py3` is an image that has been used since yolov5 supported python3.6. Currently you know yolov5 doesn't support python3.6, so pytorch should be built by yourself.
I think nvcr.io/nvidia/l4t-base can be used.
Thanks!

**Comment by joneswilliam1** [comment]
@otamajakusi Amazing! Thank you very much. Will try it out with the l4t-base image hopefully it will take a little less time build the Dockerfile :)

**Comment by joneswilliam1** [comment]
@otamajakusi update, I have just tested out building the Dockerfile with the l4t-base image and everything seems to work normally except for torch installation I receive the following error message during building:
```
Step 8/17 : RUN python3 -m pip install torch-1.8.0-cp32-cp36m-linux_aarch64.whl
 ---> Running in 6a3c3a19035a
/usr/bin/python3: No module named pip
The command '/bin/sh' -c python3 -m pip install torch-1..8.0-cp32-cp36m-linux_aarch64.whl' retured a non-zero code: 1
```

I am using previous version (which should still work) and I also tried adding the ```no-cache``` argument and still obtain the same results, I'm thinking maybe there's something else that comes with the l4t-pytorch that the base image does not, other than just torch and torchvision libraries. @otamajakusi do you maybe have any idea?

I have also have 1 more question if you don't mind, you mentioned that the l4t-pytorch image supported python3.6 however I believe recently they have updated to python3.7 in the image ```nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3``` so will this be satisfactory enough and we do not need to even build torch and torchvision from scratch or? 

Another thing is I thought that the reason you were building torch and torchvision libraries from source was because the yolov5 [requirements](https://github.com/ultralytics/yolov5/blob/cd540d8625bba8a05329ede3522046ee53eb349d/requirements.txt#L10) required higher version of torch and torchvision libraries meanwhile the l4t-pytorch did not satisfy those requirements. Is that also true?

**Comment by otamajakusi** [comment]
@joneswilliam1 
5a758413de45f454ecb08192c8ff3e6ffdbf4422 uses l4t-base. this fixes package installation problems. thanks!

>they have updated to python3.7 in the image nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3 so will this be satisfactory enough and we do not need to even build torch and torchvision from scratch or?

No. All their `nvcr.io/nvidia/l4t-pytorch:*` containers are python3.6. See https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch 
Also you can confirm by running 
```
docker run -it --rm nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3 python3 -c "import sys;import torch;print(sys.version);print(torch.__version__)"
```
So we have to build pytorch from scratch with python3.7+ to use current yolov5.
