### ISSUE TITLE
OCI runtime create failed:

### ISSUE THREAD

**Issue by PatrikPatrik2** [otamajakusi/dockerfile-yolov5-jetson#13]
Hello,

I am trrying to run the docker on a Jetson Xavier NX, with jetpack 4.6

I get this error
 `nvidia@nvidia-desktop:~/dockerfile-yolov5-jetson$ ./build.sh
Sending build context to Docker daemon  144.9kB
Step 1/20 : FROM nvcr.io/nvidia/l4t-base:r32.5.0
 ---> d9141f00a2c3
Step 2/20 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 0bb3cc1f9c51
Step 3/20 : RUN apt update
 ---> Running in a298309c1b77
failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: error adding seccomp filter rule for syscall clone3: permission denied: unknown`

How can I fix it?

**Comment by otamajakusi** [comment]
You can check this discussion:
https://forums.developer.nvidia.com/t/docker-containers-wont-run-after-recent-apt-get-upgrade/194369

**Comment by PatrikPatrik2** [comment]
That worked perfectly, thanks

`distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

sudo apt-get update
sudo apt-get install nvidia-docker2=2.8.0-1`
