### ISSUE TITLE
ImportError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by SandroToidze** [otamajakusi/dockerfile-yolov5-jetson#15]
I'm trying to run run.sh file but I keep getting this error: 

```Traceback (most recent call last):
  File "detect.py", line 41, in <module>
    from models.common import DetectMultiBackend
  File "/yolov5/models/common.py", line 14, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
```

I found that the general workaround for this problem is to do 

`export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1`

However I'm still getting the same error. I suppose that docker doesn't really care about what I'm preloading in the shell. I think this is discussed in this issue: https://github.com/sudo-project/sudo/issues/46 . Any ideas how to get this to work?

**Comment by otamajakusi** [comment]
@ArthropodDodecahedron 
Thank you for the report!
What version of L4T Linux are you using?
I'll investigate this issue this weekend.

**Comment by SandroToidze** [comment]
I'm using 4.9.253-tegra.

**Comment by otamajakusi** [comment]
> I'm using 4.9.253-tegra.

Thanks, you're using the latest Jetpack for Nano.

**Comment by SandroToidze** [comment]
Should I try downgrading? Also I can run detect.py from inside the docker container, if I do `export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1` inside the container's shell and then run it manually. Now I just need a way to make this permanent.

**Comment by otamajakusi** [comment]
adding
`-v LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1` on your docker run command works? like:
```
sudo docker run -it --rm --runtime nvidia --network host --device /dev/video0:/dev/video0:mrw -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix -v LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1 yolov5 python3.8 detect.py --source 0
```
(Sorry I don't have yolov5 jetson nano environment now)

**Comment by SandroToidze** [comment]
It does! Thanks a lot for your time

**Comment by otamajakusi** [comment]
https://github.com/otamajakusi/dockerfile-yolov5-jetson/commit/0db0bf111a62a03ab2c2bab1c1fd0776b84907db
fixes this issue. thanks!
