### ISSUE TITLE
Wrong Python Version 

### ISSUE THREAD

**Issue by Ankur-singh** [otamajakusi/dockerfile-yolov5-jetson#16]
In `README.md`, in the last command "run with your own weights", instead of `python3` it should be `python3.8`. The `run.sh` file uses `python3.8` and hence it works. But running the docker command directly doesn't work. 

This is how the commands should look:
```bash
mkdir -p /path/to/weights
cp my-weights.pt /path/to/weights
xhost +local:
docker run -it --rm \
           --runtime nvidia \
           --network host \
           --device /dev/video0:/dev/video0:mrw \
           -e DISPLAY=$DISPLAY \
           -e LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1 \
           -v /tmp/.X11-unix/:/tmp/.X11-unix \
           -v /path/to/weights:/weights \
           yolov5 python3.8 detect.py --source 0 --weights /weights/my-weights.pt
```

Also, one might run into issues related to Argus daemon. Its can be easily fixed by including `-v /tmp/argus_socket:/tmp/argus_socket`. It would really help if this information can also be added in the `README.md` file. I wasted almost two days to figure it out. For details, one can refer #3

**Comment by otamajakusi** [comment]
@Ankur-singh 
Thank you for the reporting the issue!
The issue has been fixed it at f07ef61.

**Comment by otamajakusi** [comment]
add memo to support gstreamer at 6413412.

**Comment by Ankur-singh** [comment]
Thank you so much @otamajakusi for the prompt response. It looks like both the above changes are made to `feature/yolov7` branch and not the main branch. I don't know if this was intentional or was done by mistake. I am really sorry, but I think both these changes are relevant in case of `yolov5` model as well. So, pushing it in the `main` branch would make more sense.

I might be wrong. Please correct me if I am missing something. Do you have some other use-case in mind?

**Comment by otamajakusi** [comment]
Oh, sorry, merging to feature/yolov7 is not intentional. I'll merge that changes to main, thank for the report! and sorry for confusing.

**Comment by otamajakusi** [comment]
@Ankur-singh 
Sorry, I think I can support CSI camera but it takes much time to evaluate so currently I'd like to remove CSI camera support for this docker environment.
main branch is updated.
