### ISSUE TITLE
RuntimeError: CUDA error: device kernel image is invalid

### ISSUE THREAD

**Issue by xrstokes** [otamajakusi/dockerfile-yolov5-jetson#4]
First off i want to say thanks soooooooo much!
I've been trying to get Yolo on the Jetson for three days and was about to give up when i found your repo.
So i started from scratch on my Jetson with the latest clean image. All i did was to get VNC running. Then i installed your repo.
Then i get this error;
`
>>> import torch
>>> torch.cuda.is_available()
True
>>> device = torch.device("cuda")
>>> torch.rand(10).to(device)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: device kernel image is invalid
>>> 
`

^ that was the result of a test i ran in the container. I'm going to keep trying to track it down. I'll post an update if i get to the bottom of it. But any clues would be much appreciated.

Thanks in advance.

could it be that my version is # R32 (release), REVISION: 5.1 ?

**Comment by xrstokes** [comment]
Changing back to the 5.0 image fixed the problem. But now I'm having trouble testing on an MP4. Do i need to install a lib for the MP4 format?

**Comment by xrstokes** [comment]
Another day and no progress. No matter what i try i can't open an mp4 in the container.
video = cv2.VideoCapture('all_colors.MP4')
fps = video.get(cv2.CAP_PROP_FPS)
print(fps)

^works on the jetson. but always fails in the container returning 0. That means i can't run the container with a video as the source. Any advice?

**Comment by xrstokes** [comment]
rebuilt opencv with -D OPENCV_FFMPEG_SKIP_BUILD_CHECK=ON \ 

^ fixed problem i think.

**Comment by otamajakusi** [comment]
My environment is:
```bash
jetson@jetson-desktop:~/dockerfile-yolov5-jetson$ cat /etc/nv_tegra_release 
# R32 (release), REVISION: 5.1, GCID: 26202423, BOARD: t210ref, EABI: aarch64, DATE: Fri Feb 19 16:45:52 UTC 2021
```
And I'm not good at torch, but on my environment, the instruction you mentioned doesn't show any error.
```python
root@jetson-desktop:/yolov5# python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> device = torch.device("cuda")
>>> device 
device(type='cuda')
>>> torch.rand(10)
tensor([0.9158, 0.7678, 0.5396, 0.6999, 0.3756, 0.8283, 0.8684, 0.6938, 0.5391,
        0.3479])
>>> torch.rand(10)
tensor([0.9311, 0.3135, 0.5782, 0.3391, 0.7750, 0.6705, 0.5390, 0.0953, 0.6380,
        0.4314])
>>> torch.rand(10).to(device)
tensor([0.4091, 0.0234, 0.1496, 0.8245, 0.9412, 0.9183, 0.3809, 0.7819, 0.1235,
        0.5110], device='cuda:0')
```

**Comment by otamajakusi** [comment]
> rebuilt opencv with -D OPENCV_FFMPEG_SKIP_BUILD_CHECK=ON \
> 
> ^ fixed problem i think.

I'm not sure, but I think this is not a issue for this repository, right?

**Comment by xrstokes** [comment]
Thanks for your input, It'll take me a few days to process it sorry. Just a noob tying to nut this out and there isn't a ton of information out there.
While i couldn't get it to work running the latest downloaded image from nvidia, going back to 5.0 solved it but i couldn't work out why. The running the command i mentioned on an mp4 failed because there was no link from opencv to ffmpeg. Hopefully I'm on top of it now. I'll post back here a step by step once i nail it down.

Thanks again for sharing your work.

**Comment by otamajakusi** [comment]
@xrstokes 
`print(cv2.getBuildInformation())` says:
```
...
  Video I/O:
    DC1394:                      NO
    FFMPEG:                      NO
      avcodec:                   NO
      avformat:                  NO
      avutil:                    NO
      swscale:                   NO
      avresample:                NO
    GStreamer:                   NO
    v4l/v4l2:                    YES (linux/videodev2.h)
```
So actually FFMPEG does not seem to be enabled.

**Comment by xrstokes** [comment]
any idea how i can make ffmpeg enabled? I've been trying for 2 days. I need to be able to run tests on mpegs as well as on camera.

**Comment by xrstokes** [comment]
cmake shows this.
--   Video I/O:
--     DC1394:                      YES (2.2.5)
--     FFMPEG:                      YES
--       avcodec:                   YES (57.107.100)
--       avformat:                  YES (57.83.100)
--       avutil:                    YES (55.78.100)
--       swscale:                   YES (4.8.100)
--       avresample:                YES (3.7.0)
--     GStreamer:                   YES (1.14.5)
--     v4l/v4l2:                    YES (linux/videodev2.h)

but then when it's finished. The version has changed wo i know it installed. but print(cv2.getBuildInformation()) says: NO.

weird.

**Comment by xrstokes** [comment]
DOH! It wasn't working when i installed ffmpeg with apt. If i install it with pip it works. Sorry to bother you.

**Comment by xrstokes** [comment]
ok here is my dockerfile for future reference. works with latest builds. and has ffmpeg support.
FROM nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.6-py3

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y cmake libgtk2.0-dev wget

RUN python3 -m pip install --upgrade pip

RUN python3 -m pip install ffmpeg
RUN python3 -m pip install opencv-python

RUN wget https://nvidia.box.com/shared/static/p57jwntv436lfrd78inwl7iml6p13fzh.whl -O torch-1.8.0-cp36-cp36m-linux_aarch64.whl
RUN python3 -m pip install torch-1.8.0-cp36-cp36m-linux_aarch64.whl
RUN git clone https://github.com/pytorch/vision torchvision
RUN cd torchvision && git checkout v0.9.0 && python3 setup.py install

RUN python3 -m pip install scikit-build
RUN python3 -m pip install ffmpeg
RUN python3 -m pip install opencv-python
RUN git clone https://github.com/ultralytics/yolov5.git
RUN cd yolov5 && python3 -m pip install -r requirements.txt
WORKDIR /yolov5

**Comment by otamajakusi** [comment]
@xrstokes 77c133a supports ffmpeg.

**Comment by xrstokes** [comment]
Thanks mate!
