### ISSUE TITLE
Run Yolov5 on host environment instead of container

### ISSUE THREAD

**Issue by joneswilliam1** [otamajakusi/dockerfile-yolov5-jetson#5]
Hi @otamajakusi, say I wanted to run the yolov5 on my Jetson Nano host environment instead of running it in a container (so that I could access the CSI camera for example), could I accomplish this by simply running the commands in the Dockerfile 1 by 1 on the terminal?

The only problem I see is the PyTorch 1.6.0 and Torchvision v0.7.0 installations which are pre-installed on the Base Image.

Have you ever tried running the yolov5 on the Jetson Nano host environment before and if so do you happen to have the installation steps?

Thanks and Regards!

**Comment by otamajakusi** [comment]
> Have you ever tried running the yolov5 on the Jetson Nano host environment before

Yes,

> if so do you happen to have the installation steps?

No. yolov5 on the host environment is very complicated task.

The docker file has been updated to support gstreamer (CSI-camera) at 77c133ad646b917ca0c48260a668a816b10b9702, so please consider.
See also https://github.com/otamajakusi/dockerfile-yolov5-jetson/issues/3#issuecomment-832458202

I'd like to close this issue.

**Comment by joneswilliam1** [comment]
Hi @otamajakusi, my apologies for bringing this issue back up but out of curiosity when you say that the setup on the "host environment is very complicated" are you referring to the PyTorch and Torchvision installations or some other dependencies installations which are required by the yolov5 [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt)?

Secondly, I noticed that in the Dockerfile you are using the Nvidia L4T PyTorch as the base image ([NVIDIA L4T PyTorch](https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch)) meanwhile it only comes with Torch 1.6.0 and Torchvision 0.7.0 which you do not use and you instead install Torch 1.8.0 and Torchvision 0.9.0. So my question is what is the purpose of the L4T PyTorch base image?

Thank you,
Jones
