### ISSUE TITLE
Cannot run yolov5 on Python3.6

### ISSUE THREAD

**Issue by quicktwit** [otamajakusi/dockerfile-yolov5-jetson#7]
Hi
I am running the command on terminal:
`./run.sh`
But I am getting error:
AssertionError: Python 3.7.0 required by Yolov5, but Python 3.6.9 is currently installed.

Can you help me how did you run detect.py on Python 3.6 on Jetson Nano?
Thank you in advance.

**Comment by otamajakusi** [comment]
I'm afraid jetpack might be old.
Please make sure that the jetpack is v5.0.

**Comment by quicktwit** [comment]
Ok you're right. Now it make sense. Thank you so much. I will upgrade and see if it works. I will close the issue. Anyways I can able to use this Dockerfile of yours: https://gist.github.com/otamajakusi/69637ad482ca11f7e86ec7d9b4586285 for Python3.6.
Thank you
