### ISSUE TITLE
Jetsonnano + YOLOv5 could not work on python 3.6.9

### ISSUE THREAD

**Issue by okome-git** [otamajakusi/dockerfile-yolov5-jetson#8]
Thanks for your useful repository!! 
I met this type of error 
"AssertionError: Python 3.7.0 required by YOLOv5, but Python 3.6.9 is currently installed"
How can I figure out ?

#I can read japanese.

**Comment by otamajakusi** [comment]
I think your jetpack should be updated to 4.5 or higher.
Try it!

**Comment by quicktwit** [comment]
I had the similar issue. Try this comment: [Run yolov5 on Jetson Nano](https://github.com/otamajakusi/dockerfile-yolov5-jetson/issues/7#issuecomment-839318427)

**Comment by okome-git** [comment]
I updated to jetpack 4.5 today.
And, it didn't not work...
There was same issue
"AssertionError: Python 3.7.0 required by YOLOv5, but Python 3.6.9 is currently installed"

**Comment by otamajakusi** [comment]
Ok, I'd like to confirm this weekend.

**Comment by okome-git** [comment]
Thanks !!

**Comment by otamajakusi** [comment]
recent commits at yolov5, https://github.com/ultralytics/yolov5/pull/3088, requires python3.7 or higher.
I'd like to fix this issue. thanks.

**Comment by okome-git** [comment]
Thank you for your kindness !

Do you know which commit of yolov5 is suitable for jetpack 4.5 ?

**Comment by otamajakusi** [comment]
@okome-git 
before https://github.com/ultralytics/yolov5/pull/3088, I think 91547edec1a33121b3607e8c946e051514182b4f can be used, like this:
```patch
diff --git a/Dockerfile b/Dockerfile
index 3b46f20..8dfe8e4 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -19,5 +19,6 @@ RUN git clone --recursive https://github.com/skvark/opencv-python.git
 RUN python3 -m pip install --upgrade pip
 RUN cd opencv-python && python3 -m pip wheel . --verbose && find . -name "opencv_python*.whl" | xargs python3 -m pip install
 RUN git clone https://github.com/ultralytics/yolov5.git
+RUN git checkout 91547edec1a33121b3607e8c946e051514182b4f
 RUN cd yolov5 && python3 -m pip install -r requirements.txt
 WORKDIR /yolov5
```

**Comment by okome-git** [comment]
It works !
Thank you!!

**Comment by phongvu0403** [comment]
Hello, I have same issue "AssertionError: Python 3.7.0 required by YOLOv5, but Python 3.6.9 is currently installed". I installed jetpack 4.5.1. In my Jetson Nano, Python version default is 3.6.9 then I installed Python 3.7.5 and I point python3 to python3.7. So when I type "python3 --version", terminal show "python 3.7.5". But this problem still exists.
Can you help me?
Thank advance

**Comment by otamajakusi** [comment]
Currently https://github.com/otamajakusi/dockerfile-yolov5-jetson/issues/8#issuecomment-846356393 is the only workaround for this issue.
Even if you install python3.7 on the docker environment, pytorch can not be worked.

**Comment by phongvu0403** [comment]
I think you should set `cd yolov5` before `git checkout 91547edec1a33121b3607e8c946e051514182b4f`.

**Comment by okome-git** [comment]
@phongvu0403 
It works using "git checkout 91547edec1a33121b3607e8c946e051514182b4f".
But I could not use my custom training weights, because of "_pickle.UnpicklingError" like below,

Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, hide_conf=False, hide_labels=False, img_size=640, iou_thres=0.45, line_thickness=3, name='exp', nosave=False, project='runs/detect', save_conf=False, save_crop=False, save_txt=False, source='data/images', update=False, view_img=False, weights=['../yolov5_01/my_yolov5s.pt'])
YOLOv5 \U0001f680 v5.0-75-g91547ed torch 1.8.0 CUDA:0 (NVIDIA Tegra X1, 3964.1328125MB)

Traceback (most recent call last):
  File "detect.py", line 181, in <module>
    detect(opt=opt)
  File "detect.py", line 33, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/yolov5/models/experimental.py", line 120, in attempt_load
    ckpt = torch.load(w, map_location=map_location)  # load
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '-'.

**Comment by phongvu0403** [comment]
@okome-git 
I modified the Dockerfile following the author's instructions. However, there is 1 error here:

Step 15/18 : RUN git clone https://github.com/ultralytics/yolov5.git
 ---> Running in 0fd30920640d
Cloning into 'yolov5'...
Removing intermediate container 0fd30920640d
 ---> e70d45f62147
Step 16/18 : RUN git checkout 91547edec1a33121b3607e8c946e051514182b4f
 ---> Running in 08ab50a200dc
fatal: not a git repository (or any of the parent directories): .git
The command '/bin/sh -c git checkout 91547edec1a33121b3607e8c946e051514182b4f' returned a non-zero code: 128

Can you help me fixed this problem?
Thank you!

**Comment by otamajakusi** [comment]
workaround is add at c46325b7961f00ccf6624b5a61f795a92179c991
and default branch is changed to `war-python36`, since this is a workaround, not a solution.
please fetch and change your branch to `war-python36`.

**Comment by otamajakusi** [comment]
3c8e9465bc6b2dd170c9547be65bb316ac24803a supports python3.8 and default branch has been changed to `main`.
In this commit, pre-build pytorch binary is used, which was build with https://github.com/otamajakusi/dockerfile-pytorch-build-jetson repo.
thanks.
